attention_probs_dropout_prob: 0.0
decoder_hidden_size: 256
decoder_intermediate_size: 512
decoder_num_attention_heads: 4
decoder_num_hidden_layers: 2
hidden_act: "gelu"
hidden_dropout_prob: 0.0
hidden_size: 256 # размерность скрытого слоя
# input_embedding_dim: 512
# size: 512
initializer_range: 0.02
intermediate_size: 1024
layer_norm_eps: 1e-12
mask_ratio: 0.0
model_type: "vit_mae"
norm_pix_loss: false
num_attention_heads: 4
num_channels: 3
num_hidden_layers: 4 
image_size: 256
patch_size: 16
qkv_bias: true
is_load_pretrained: True
pretrained_model_name: "unimodal_wsi_800_mae_2conv_all_data_balanced/unimodal_wsi_800_mae_2conv_all_data_balanced"
pretrained_model_path: ""
output_dim: 20
max_patches_per_sample: 10
num_patches: 10
random_patch_selection: True
use_transformer_pool: False
#pretrained_model_path: "facebook/vit-mae-base"
embeddings_layers:
  - name: "Conv2d"
    args: [3, 16, 4]
    kwargs: 
      stride: 4
  - name: "GELU"
  - name: "Conv2d"
    args: [16, 256, 4]
    kwargs: 
      stride: 4

decoder_pred_layers:
  - name: "ConvTranspose2d"
    args: [256, 16, 4]
    kwargs:
      stride: 4
  - name: "GELU"
  - name: "ConvTranspose2d"
    args: [16, 3, 4]
    kwargs:
      stride: 4