attention_probs_dropout_prob: 0.0
decoder_hidden_size: 32
decoder_intermediate_size: 32
decoder_num_attention_heads: 4
decoder_num_hidden_layers: 2
hidden_act: "gelu"
hidden_dropout_prob: 0.0
hidden_size: 32 # maybe 384?
initializer_range: 0.02
intermediate_size: 32
layer_norm_eps: 1e-12
mask_ratio: 0.5
model_type: "vit_mae"
norm_pix_loss: false
num_attention_heads: 4
num_channels: 1
num_hidden_layers: 4
qkv_bias: true

patch_size: 8 #
mri_size: 64

#survival-specific
is_load_pretrained: true
pretrained_model_name: "mri_mae_pretrain_t1c_dummy_test"
output_dim: 20 #should 

