defaults: 
  # - base@stages.pretrain.base: mri_diffusion_pretrain
  # - model@stages.pretrain.model: mri_diffusion_pretrain
  # - data@stages.pretrain.data: mri_mae
  - base@stages.task.base: mri_diffusion_model
  - model@stages.task.model: mri_diffusion_model
  - data@stages.task.data: mri_mae
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
  - _self_

debug: True

hydra:
  mode: MULTIRUN
  sweeper:
    direction: maximize #!!! CHECK BEFORE LAUNCH !!!
    study_name: mri_diffusion_t1c_no_time_sample_prediction
    storage: null
    n_trials: 2
    n_jobs: 1
    params:
      stages.task.model.pretrained_model_name: choice("mri_diffusion_pretrain_t1c_no_time_sample_prediction_800", "mri_diffusion_pretrain_t1c_no_time_sample_prediction")

stages:
  # pretrain:
  #   metric: "mse_loss.mean"
  #   base:
  #     experiment_name: "mri_diffusion_pretrain_t1c_no_time_sample_prediction_800"
  #     n_epochs: 800
  #     splits: 5
    
  task:
    metric: "cs_score.mean"
    base:
      experiment_name: "mri_diffusion_model_t1c_no_time_sample_prediction_100"
      n_epochs: 100
      splits: 5
    model:
      pretrained_model_name: ???
      is_load_pretrained: true