defaults: 
    - model: wsi_base
    - base: unimodal_wsi
    - dataset: wsi_base
base:
    experiment_name: "wsi base from article"
    n_epochs: 50
    n_intervals: 20
    random_seed: 1380

    optimizer:
        name: "AdamW"
        params:
            lr: 1e-3
            weight_decay: 1e-2
    
    scheduler: 
        name: "CosineAnnealingLR"
        params:
            eta_min: 5e-6


    type: "unimodal"
    strategy: "survival" # mae, survival
    modalities: ["wsi"] #rna, mri
    splits: 5
    data_path: "src/data/dataset.csv"
    root_path: "../"
    save_path : "outputs/models/"
    device: "cuda:0"
    remove_nan_column: 'WSI'
    batch_size: 24

    log:
        logging: True
        wandb_project: "cancer_mtcp"
        wandb_run_name: ${base.experiment_name}
