experiment_name: "mri_mae_pretrain_t1c_test"
n_epochs: 2
splits: 1
random_seed: 1380

optimizer:
    name: "AdamW"
    params:
        lr: 2e-5
        weight_decay: 1e-2

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6


type: "unimodal"
strategy: "mae" # mae, survival
modalities: ["mri"] #rna, mri
data_path: "src/data/pretrain_mri_t1c_t1n_t2w_t2f.csv"
root_path: "../"
save_path : "outputs/models/"
device: "cuda:0"
remove_nan_column: 'MRI'
batch_size: 24
num_workers: 8

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: ${base.experiment_name}

profiling:
    sort_by_keyword: self_cuda_time_total #by which parameter profiler output should be sorted
    row_limit: 10 #how many rows should be in profiler output
    is_print: True