experiment_name: "mri_mae_model_t1c_num_layers_enc_${model.num_hidden_layers}_dec_${model.decoder_num_hidden_layers}_test"
splits: 1
n_epochs: 2

n_intervals: 20
random_seed: 1380

optimizer:
    name: "AdamW"
    params:
        lr: 2e-5
        weight_decay: 1e-2

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6


type: "unimodal"
strategy: "survival" # mae, survival
modalities: ["mri"] #rna, mri
architecture: "MAE"
data_path: "src/data/dataset.csv"
root_path: "../"
save_path : "outputs/models/"
device: "cuda:0"
remove_nan_column: 'MRI'
batch_size: 24
num_workers: 8

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: ${base.experiment_name}

profiling:
    sort_by_keyword: self_cuda_time_total #by which parameter profiler output should be sorted
    row_limit: 10 #how many rows should be in profiler output
    is_print: True