defaults:
  - log: dwemer8

experiment_name: "multimodal_rna_dnam_wsi10_mean1e4_gelu_GBMLGG_with_pretraining_survival"
n_epochs: 20
warmup_epochs: 5 
n_intervals: 20
random_seed: 1380

optimizer:
    name: "AdamW"
    params:
        lr: 1e-4 # 2e-5
        weight_decay: 1e-2

optimizer_unimodal:
    rna:
        name: "AdamW"
        params:
            lr: 1e-3 # 2e-5
            weight_decay: 1e-2
    dnam:
        name: "AdamW"
        params:
            lr: 1e-4 # 2e-5
            weight_decay: 1e-2
    wsi:
        name: "AdamW"
        params:
            lr: 1e-4 # 2e-5
            weight_decay: 1e-2             

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

scheduler_unimodal: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6    

loss:
    additional_loss: "CoxPHLoss"
    alpha: 0.7

type: "multimodal"
strategy: "survival" # mae, survival
sampler: True

modalities: ["rna", "dnam", "wsi"]

multimodal_intersection_test: true
architecture: "MAE"
splits: 5
save_path : "outputs/models/"
project_ids: ["GBM", "LGG"]


data_path: "src/data/dataset_inetrsection_all_v2.csv"
rna_dataset_path: "src/data/rna_dataset_full_tcga.csv"
device: "cuda:0"

#available_gpus:  [0]  # Указываем, какие GPU можно использовать
remove_nan_column: 'RNA'
batch_size: 24

# early_stopping:
#     early_stopper:
#         patience: 7
#         eps: 0
#         smoothing: "running_average"
#         smoothing_period: 5
#         direction: "min"
#     value_to_track: "task_loss"

# early_stopping:
#     early_stopper:
#         patience: 5
#         eps: 0
#         smoothing: "no_smoothing"
#         smoothing_period: 1
#         direction: "max"
#     value_to_track: "c_index"