defaults:
    - log: dwemer8

experiment_name: "rsna_mae_survival_random_final_version"
n_epochs: 20
warmup_epochs: 5 
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 2e-5
        weight_decay: 1e-2

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6


type: "unimodal"
strategy: "survival" # mae, survival
modalities: ["rna"]
architecture: "MAE"
splits: 5

root_path: "../"
save_path : "outputs/models/"
data_path: "src/data/dataset_inetrsection_all_v2.csv"
rna_dataset_path: "src/data/rna_dataset_full_tcga.csv"
device: "cuda:3"
remove_nan_column: 'RNA'
batch_size: 24
project_ids: ["GBM", "LGG"]
sampler: True
loss:
    additional_loss: "CoxPHLoss"
    alpha: 0.7