experiment_name: "rsna_mae_clusters_survival_800_september"
n_epochs: 1600
warmup_epochs: 50
n_intervals: 20
random_seed: 1380

optimizer:
    name: "AdamW"
    params:
        lr: 1e-4
        weight_decay: 0.05
    
scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

type: "unimodal"
strategy: "mae" # mae, survival
modalities: ["rna"]
architecture: "MAE"
splits: 5
root_path: "../"
save_path : "outputs/models/"
data_path: "src/data/dataset_full_tcga_all_balanced.csv"
rna_dataset_path: "src/data/rna_dataset_full_tcga_go.csv"
device: "cuda:0"
remove_nan_column: 'RNA'
batch_size: 64

log:
    logging: True
    logging_platform: "neptune"
    project_name: "almachan2358/cancer-mtcp"
    run_name: "survival1"
    api_token: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI1Nzg4MGQxNS0zMjM1LTQ4NTUtYTViYy01ZjExNWU4N2JiOTYifQ=="


