experiment_name: "wsi mae"
splits: 1
n_epochs: 2

n_intervals: 20
random_seed: 1380

optimizer:
    name: "AdamW"
    params:
        lr: 2e-5
        weight_decay: 1e-2

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6


type: "unimodal"
strategy: "mae" # mae, survival
modalities: ["wsi"] #rna, mri
architecture: "MAE"
data_path: "/home/a.beliaeva/mtcp/updated_utf8.csv"
root_path: "../"
save_path : "/home/a.beliaeva/mtcp/src/outputs/models/main_mae/"
device: "cuda:2"
remove_nan_column: 'WSI_initial'
batch_size: 2
num_workers: 2

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: ${base.experiment_name}

profiling:
    sort_by_keyword: self_cuda_time_total #by which parameter profiler output should be sorted
    row_limit: 10 #how many rows should be in profiler output
    is_print: True